[package]
name = "ekotrace-header-gen"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
sha2 = "0.8"
