[package]
name = "truce-c"
version = "0.1.0"
authors = ["Zachary Pierce <zack@auxon.io>"]
edition = "2018"

[lib]
name = "trucec"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
truce = { path = "../" }
libc = "0.2"

[build-dependencies]

[workspace]