[workspace]
members = [
  "alloc-log-report",
  "ekotrace",
  "ekotrace-analysis",
  "ekotrace-capi-impl",
  "ekotrace-header-gen",
  "ekotrace-event-manifest-gen",
  "ekotrace-udp-collector",
  "test-support/proc-graph",
]
