[package]
name = "modality-probe"
version = "0.3.0"
authors = [
    "Zachary Pierce <zack@auxon.io>",
    "Russell Mull <russell@auxon.io>",
    "dan pittman <dan@auxon.io>",
    "Jon Lamb <jon@auxon.io>"
]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/auxoncorp/modality-probe"
readme = "README.md"

[features]
default = []
std = ["serde", "proptest", "schemars"]

[workspace]
members = [
  "modality-probe-cli",
  "collectors/modality-probe-udp-collector",
  "collectors/modality-probe-collector-common",
]
exclude = ["debian-package", "./collectors"]

[dependencies]
static_assertions = "1.1.0"
fixed-slice-vec = "0.2"
byteorder = { version = "1.3", default-features = false }

# Used if the std feature is enabled.
serde = { version = "1.0", features = ["derive"], optional = true }
proptest = { version = "0.9.5", optional = true }
schemars = { version = "0.6.5", optional = true }