[package]
name = "modality-probe-debug-collector"
version = "0.1.0"
authors = ["Nicholas Springer <nspringer@auxon.io>"]
edition = "2018"

[dependencies]
goblin = "0.2.3"
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.3"
parse_duration = "2.1.0"
probe-rs = "0.7.1"
maplit = "1.0.2"
tempfile = "3.1.0"
err-derive = "0.2.4"
ctrlc = "3.1.6"
crossbeam-channel = "0.4.3"

fenced-ring-buffer = { path = "../../fenced-ring-buffer", features = ["std"] }
modality-probe = { path = "../..", features = ["debug-collector-access"] }
modality-probe-collector-common = { path = "../modality-probe-collector-common" }