[package]
name = "ekotrace-capi"
version = "0.1.0"
authors = ["Zachary Pierce <zack@auxon.io>"]
edition = "2018"

[lib]
name = "ekotrace_capi"
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["default_panic_impl"]
default_panic_impl = []

[dependencies]
ekotrace = { path = "../ekotrace" }

[build-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
