[package]
name = "race-buffer"
version = "0.1.0"
authors = ["Nicholas Springer <nspringer@auxon.io>"]
edition = "2018"

[dev-dependencies]
crossbeam = "0.7.3"
rand = "0.7.3"

[features]
default = []
std = []