[package]
name = "truce-analysis"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
csv = "1.1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
proptest = "0.9.4"
