name: Build and Test

on: [pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: sudo apt-get install -y libusb-1.0-0-dev
      - name: install dot
        run: sudo apt-get install -y graphviz

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-07-12
          override: true
          components: rustfmt, clippy

      # Used by debug-collector tests to generate binaries
      - name: Install thumbv7em-none-eabihf target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true

      - name: Fetch dependencies
        uses: actions-rs/cargo@v1
        with:
          command: fetch

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Test
        run: ./test.sh

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings

      - name: Run cargo fmt (capi)
        run: |
          cd modality-probe-capi
          cargo fmt -- --check

      - name: Run cargo clippy (capi)
        run: |
          cd modality-probe-capi
          cargo clippy --all

      - name: Test (big endian target)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          # Exclude debug collector because libusb is required to build
          args: --all --exclude modality-probe-debug-collector --features "std" --target=mips64-unknown-linux-gnuabi64

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # Used by debug-collector tests to generate binaries
      - name: Install thumbv7em-none-eabihf target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true

      - name: Fetch dependencies
        uses: actions-rs/cargo@v1
        with:
          command: fetch

      # Windows MSVC doesn't like the no-std modality-probe-capi cdylib build
      - name: Test
        shell: bash
        run: ./test.sh windows
